#!/usr/bin/env bash
set -ex

here=$(dirname $0)
git_id=$(git rev-parse --short=7 HEAD)

registry=docker.montagu.dide.ic.ac.uk:5000
name=naomi_bot

if [ "$1" = "--use-vault" ]; then
    . $here/vault_auth.sh
fi

docker run -d \
    -p 4567:80 \
    --name naomi_bot \
    $registry/$name:$git_id