#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

pip3 install --quiet -r requirements.txt
python3 -m pytest

docker build -t $COMMIT_TAG -t $BRANCH_TAG -f docker/Dockerfile .
docker push $COMMIT_TAG
docker push $BRANCH_TAG