#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

pip3 install --quiet --upgrade pip
pip3 install --quiet -r requirements.txt
python3 -m pytest

docker build --pull \
       -t $TAG_SHA \
       -f docker/Dockerfile \
       $PACKAGE_ROOT

docker push $TAG_SHA