#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

function cleanup {
    set +e
    rm $HERE/.vault_secrets.ini -f
}
trap cleanup EXIT

if [ "$1" = "--use-vault" ]; then
    . $HERE/vault_auth.sh
fi

## create a tmp file and write secrets out 
. $HERE/vault_secrets

docker pull $TAG_BRANCH

docker run -d \
    --restart=always \
    -p 4568:80 \
    --name naomi_bot \
    $TAG_BRANCH

docker cp $HERE/.vault_secrets.ini naomi_bot:/app/vault_secrets.ini
