#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

if [ "$1" = "--use-vault" ]; then
    . $here/vault_auth.sh
fi

docker run -d \
    -p 4568:80 \
    --name naomi_bot \
    $REGISTRY/$NAME:$GIT_ID