#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)

export VAULT_ADDR='https://support.montagu.dide.ic.ac.uk:8200'
vault login -method=github > /dev/null
HINTR_SECRET=`vault read -field=repo /secret/naomi-bot/hintr`
GH_AUTH_TOKEN=`vault read -field=token /secret/naomi-bot/auth-token`
echo "[vault_secrets]
HINTR_SECRET=${HINTR_SECRET}
GH_AUTH_TOKEN=${GH_AUTH_TOKEN}
" >> $HERE/.vault_secrets.ini