#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)

export VAULT_ADDR='https://vault.dide.ic.ac.uk:8200'
vault login -method=github > /dev/null
WEBHOOK_SECRET=`vault read -field=secret /secret/hint/naomi-bot/webhook-secret`
GH_AUTH_TOKEN=`vault read -field=token /secret/vimc-robot/github-pat`
echo "[vault_secrets]
WEBHOOK_SECRET=${WEBHOOK_SECRET}
GH_AUTH_TOKEN=${GH_AUTH_TOKEN}
" >> $HERE/.vault_secrets.ini